### ISSUE TITLE
Problems in Ubuntu 20.04

### ISSUE THREAD

**Issue by sebbleroni** [bankrasrg/usbtc08#9]
I was trying to install the package according to the instructions which worked well on my old Ubuntu 18.04 system. The installation itself did not give any error, however importing the module via

```python
import usbtc08
```
throws an  ``ÌnportError``:

```bash
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/usbtc08.py", line 15, in <module>
    import _usbtc08
ImportError: /usr/local/lib/python3.8/dist-packages/_usbtc08.cpython-38-x86_64-linux-gnu.so: undefined symbol: usb_tc08_legacy_get_cycle
```

Has someone possibly encountered this problem before and if yes, how have you been able to solve it?

Very kind regards!

**Comment by vhulagov** [comment]
Try this:
```
wget https://labs.picotech.com/debian/pool/main/libu/libusbtc08/libusbtc08_2.0.17-1r1441_amd64.deb
sudo dpkg -i ./libusbtc08_2.0.17-1r1441_amd64.deb
sudo ln -s /opt/picoscope/include/libusbtc08 /opt/picoscope/include/libusbtc08-1.8
swig -python usbtc08.i
```
I hope I will refresh this script to version with python3 and paho (MQTT) soon...
